name: pyinstaller
on: workflow_dispatch

jobs:

  build-on-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: check env
        run: |
          env
