name: pyinstaller
on: workflow_dispatch

jobs:

  build-on-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v3
        with:
          name: sha256-linux
          path: dist/sha256

  test-build-linux:
    runs-on: ubuntu-22.04
    needs: build-on-linux
    steps:
      - names: download binary file
        uses: actions/download-artifact@v3
        with:
          name: sha256-linux
      - name: test binary file
        run: |
          ls
          chmod +x sha256
          ./sha256 sha256
